# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03194e8fc6bfa040c19bbf4c313f983eb981bc6bbcb090369f26324a375a4fe2142e995942300cd22c2d1fae934296f1bcff021822230f7ac71cc06af978c004

test:
  secret_key_base: 70b70c2111515acfd3c166326810d31b36e15299df28278c219c21f016d28e899832e580f150dc704c552e70a1f4c6813c06ea1f67600ce7e6af48a9c46b173c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
